[package]
name = "sol-tools"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
actix-files = { version = "0.6", optional = true }
actix-web = { version = "4.0", optional = true }
console_error_panic_hook = "0.1"
http = { version = "1.0.0", optional = true }
leptos = { version = "0.6.5" }
leptos_meta = { version = "0.6.5" }
leptos_actix = { version = "0.6.5", optional = true }
leptos_router = { version = "0.6.5" }
wasm-bindgen = "0.2.93"
web-sys = { version = "0.3", features = [
    "Event",
    "SubmitEvent",
    "HtmlElement",
    "Window",
    "Document",
    "Storage",
    "Performance",
    "File",
    "FileList",
    "HtmlInputElement"
]}
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
gloo-utils = "0.2"
serde_json = "1.0"
anyhow = "1.0"
serde-wasm-bindgen = "0.6"
borsh = { version = "0.10.3", features = ["derive"] }
url = { version = "2.5.0", features = ["serde"] }

# Server-side only dependencies
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
solana-program = { version = "1.16.0", features = ["borsh"] }
solana-client = "1.16.0"
solana-sdk = { version = "1.16.0", features = ["borsh"] }
spl-token = { version = "4.0", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "2.2", features = ["no-entrypoint"] }
mpl-token-metadata = { version = "1.13", features = ["no-entrypoint"] }
tokio = { version = "1.21", features = ["macros", "rt-multi-thread"] }
dotenv = "0.15.0"
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
base58 = "0.1.0"
actix-web = { version = "4.0", features = ["macros"] }

[features]
csr = ["leptos/csr", "leptos_meta/csr", "leptos_router/csr"]
hydrate = ["leptos/hydrate", "leptos_meta/hydrate", "leptos_router/hydrate"]
ssr = [
  "dep:actix-files",
  "dep:actix-web",
  "dep:leptos_actix",
  "leptos/ssr",
  "leptos_meta/ssr",
  "leptos_router/ssr",
  "dep:http"
]

[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"

[package.metadata.leptos]
output-name = "sol-tools"
site-root = "target/site"
site-pkg-dir = "pkg"
style-file = "style/main.scss"
assets-dir = "assets"
site-addr = "127.0.0.1:3000"
reload-port = 3001
end2end-cmd = "npx playwright test"
end2end-dir = "end2end"
browserquery = "defaults"
env = { "PINATA_API_KEY" = "", "PINATA_SECRET_API_KEY" = "", "SOLANA_SECRET_KEY" = "" }
bin-features = ["ssr"]
bin-default-features = false
lib-features = ["hydrate"]
lib-default-features = false
lib-profile-release = "wasm-release"
bin-target = "sol-tools"
