[package]
name = "sol-tools"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# Core dependencies
leptos = { version = "0.6.15", features = ["nightly"] }
leptos_meta = { version = "0.6.15", features = ["nightly"] }
leptos_router = { version = "0.6.15", features = ["nightly"] }
leptos_actix = { version = "0.6.15", optional = true }
console_error_panic_hook = "0.1"
log = "0.4"
env_logger = { version = "0.11", optional = true }

# WASM dependencies
wasm-bindgen = "0.2.86"
wasm-bindgen-futures = "0.4.36"
web-sys = { version = "0.3", features = [
    "Window", "Document", "Element", "HtmlElement", 
    "File", "Blob", "Url", "Response", "Headers",
    "RequestInit", "RequestMode", "Request",
    "Crypto", "SubtleCrypto", "CryptoKey",
    "DomStringMap", "Storage", "Performance",
    "PerformanceTiming", "console"
]}
js-sys = "0.3"
getrandom = { version = "0.2", features = ["js"] }
gloo = { version = "0.11", features = ["storage"] }

# Server dependencies
actix-web = { version = "4.4", features = ["macros"], optional = true }
actix-files = { version = "0.6.2", optional = true }
actix-rt = { version = "2.9", optional = true }
tokio = { version = "1.28", features = ["rt-multi-thread", "macros", "fs", "io-util", "net"], optional = true }
futures = { version = "0.3", optional = true }
reqwest = { version = "0.11.27", default-features = false, features = ["json"], optional = true }

# Solana dependencies
solana-program = { version = "1.18" }
solana-sdk = { version = "1.18" }
solana-client = { version = "1.18" }
spl-token = "4.0"
spl-associated-token-account = "2.0"
spl-token-2022 = "0.9"
mpl-token-metadata = "4.0"
mpl-token-auth-rules = "1.4"
bs58 = "0.5"

# Error handling
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
borsh = "0.10.3"

# Add sha2 for cryptographic hashing
sha2 = "0.10"

[features]
default = ["ssr", "hydrate"]
hydrate = [
    "leptos/hydrate",
    "leptos_meta/hydrate",
    "leptos_router/hydrate"
]
ssr = [
    "dep:actix-web",
    "dep:actix-files",
    "dep:actix-rt",
    "dep:tokio",
    "dep:futures",
    "dep:reqwest",
    "dep:env_logger",
    "dep:leptos_actix",
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr"
]

[package.metadata.leptos]
output-name = "sol-tools"
site-root = "target/site"
site-pkg-dir = "pkg"
site-addr = "127.0.0.1:3000"
reload-port = 3001
env = "DEV"
bin-target = "sol-tools"
style-file = "style/main.scss"
assets-dir = "assets"
site-root-relative = true
lib-profile-release = "wasm-release"
lib-profile-dev = "dev"
browserquery = "defaults"
watch = true
watch-additional-files = ["./src/**/*"]
features = ["ssr", "hydrate"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
reqwest = { version = "0.11.27", features = ["json", "rustls-tls"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
reqwasm = "0.5.0"
serde-wasm-bindgen = "0.6"
