[package]
name = "sol-tools"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "sol-tools"
path = "src/main.rs"

[[bin]]
name = "create_spl"
path = "src/bin/create_spl.rs"

[dependencies]
# Core dependencies
leptos = { version = "0.6.5", features = ["nightly"] }
leptos_meta = { version = "0.6.5", features = ["nightly"] }
leptos_router = { version = "0.6.5", features = ["nightly"] }
leptos_actix = { version = "0.6.5", optional = true }
console_error_panic_hook = "0.1"
log = "0.4"

# WASM dependencies
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Window", "Document", "File"] }
js-sys = "0.3"

# Server-only dependencies
tokio = { version = "1", features = ["full"], optional = true }
actix-files = { version = "0.6", optional = true }
actix-web = { version = "4", optional = true }
http = { version = "1.0.0", optional = true }
mio = { version = "0.8", optional = true }

# Shared dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
dotenv = "0.15"
borsh = "0.10.3"

# Token-related dependencies
mpl-token-metadata = { version = "1.9.1", features = ["no-entrypoint"] }
mpl-token-auth-rules = "1.3"

[features]
default = ["hydrate", "ssr"]
hydrate = [
    "leptos/hydrate", 
    "leptos_meta/hydrate", 
    "leptos_router/hydrate"
]
ssr = [
    "dep:actix-files",
    "dep:actix-web",
    "dep:leptos_actix",
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr",
    "dep:tokio",
    "dep:http",
    "dep:mio"
]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
solana-program = "1.16"
solana-client = "1.16"
solana-sdk = "1.16"
spl-token = "3.5"
spl-token-2022 = "0.9"
spl-associated-token-account = "1.1"
mpl-token-metadata = { version = "1.9.1", features = ["no-entrypoint"] }
mpl-token-auth-rules = "1.3"

[workspace]
members = ["."]

[[workspace.metadata.leptos]]
name = "sol-tools"
bin-package = "sol-tools"
bin-target = "sol-tools"
lib-package = "sol-tools"
output-name = "sol-tools"
root = "."
