[package]
name = "sol-tools"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# Core dependencies
leptos = "0.6.15"
leptos_meta = "0.6.15"
leptos_router = "0.6.15"
console_error_panic_hook = "0.1"
log = "0.4"

# WASM dependencies
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Window", "Document", "File"] }
js-sys = "0.3"

# Shared dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
borsh = "0.10.3"
getrandom = { version = "0.2", features = ["js"] }

# Optional server-only dependencies
actix-web = { version = "4", default-features = false, features = ["rustls"], optional = true }
actix-files = { version = "0.6", optional = true }
leptos_actix = { version = "0.6.6", optional = true }
tokio = { version = "1", features = ["full"], optional = true }
http = { version = "0.2", optional = true }
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"], optional = true }
dotenv = { version = "0.15", optional = true }

# Solana and related dependencies (optional)
solana-program = { version = "1.16.14", optional = true }
solana-sdk = { version = "1.16.14", optional = true }
solana-client = { version = "1.16.14", optional = true }
spl-token = { version = "4.0.0", optional = true }
spl-associated-token-account = { version = "2.0.0", optional = true }
spl-token-2022 = { version = "0.9.0", optional = true }
mpl-token-metadata = { version = "5.1.0", optional = true }
mpl-token-auth-rules = { version = "1.5.1", optional = true }

[features]
default = []
ssr = [
    "actix-web",
    "actix-files",
    "leptos_actix",
    "tokio",
    "http",
    "reqwest",
    "dotenv",
    "solana-program",
    "solana-sdk",
    "solana-client",
    "spl-token",
    "spl-associated-token-account",
    "spl-token-2022",
    "mpl-token-metadata",
    "mpl-token-auth-rules",
]

[workspace]
members = ["."]

[package.metadata.leptos]
output-name = "sol-tools"
site-root = "target/site"
site-pkg-dir = "pkg"
site-addr = "127.0.0.1:3000"
reload-port = "3001"
env = "DEV"

# Specify the server binary and features
server-path = "src/main.rs"
additional-features = ["ssr"]

# Client build configurations
client-features = []
client-default-features = false

# Server build configurations
server-features = ["ssr"]
server-default-features = false
