[package]
name = "sol-tools"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# Core dependencies
leptos = { version = "0.6.15", features = ["nightly"] }
leptos_meta = { version = "0.6.15", features = ["nightly"] }
leptos_router = { version = "0.6.15", features = ["nightly"] }
leptos_actix = { version = "0.6.15", optional = true }
console_error_panic_hook = "0.1"
log = "0.4"

# WASM dependencies
wasm-bindgen = "0.2.95"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Window", "Document", "File", "Crypto", "SubtleCrypto"] }
js-sys = "0.3"
getrandom = { version = "0.2", features = ["js"] }
ring = { version = "0.17", features = ["wasm32_unknown_unknown_js"] }

# Shared dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
borsh = "0.10.3"

# Server dependencies
actix-web = { version = "4.4", features = ["macros"], optional = true }
actix-files = { version = "0.6.2", optional = true }
actix-rt = { version = "2.9", optional = true }
tokio = { version = "1.36", features = ["rt-multi-thread", "macros", "fs", "io-util", "net"], optional = true }
tokio-util = { version = "0.7.10", features = ["io"], optional = true }
futures = { version = "0.3", optional = true }
http = { version = "0.2", optional = true }
reqwest = { version = "0.11", features = ["json", "native-tls-vendored"], optional = true }
dotenv = { version = "0.15", optional = true }

# Solana dependencies - aligned versions
solana-program = { version = "1.18", optional = true }
solana-sdk = { version = "1.18", optional = true }
solana-client = { version = "1.18", optional = true }
spl-token = { version = "4.0", optional = true }
spl-associated-token-account = { version = "2.0", optional = true }
spl-token-2022 = { version = "0.9", optional = true }
mpl-token-metadata = { version = "4.0", optional = true }
mpl-token-auth-rules = { version = "1.4", optional = true }

# Error handling
anyhow = "1.0"

[features]
default = ["ssr", "hydrate"]
hydrate = [
    "leptos/hydrate",
    "leptos_meta/hydrate",
    "leptos_router/hydrate"
]
ssr = [
    "dep:actix-web",
    "dep:actix-files",
    "dep:actix-rt",
    "dep:tokio",
    "dep:tokio-util",
    "dep:futures",
    "dep:http",
    "dep:reqwest",
    "dep:dotenv",
    "dep:solana-program",
    "dep:solana-sdk",
    "dep:solana-client",
    "dep:spl-token",
    "dep:spl-associated-token-account",
    "dep:spl-token-2022",
    "dep:mpl-token-metadata",
    "dep:mpl-token-auth-rules",
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr"
]

[package.metadata.leptos]
output-name = "sol-tools"
site-root = "target/site"
site-pkg-dir = "pkg"
site-addr = "127.0.0.1:3000"
reload-port = 3001
env = "DEV"
bin-target = "sol-tools"
style-file = "style/main.scss"
assets-dir = "assets"
site-root-relative = true
lib-profile-release = "wasm-release"
lib-profile-dev = "dev"
browserquery = "defaults"
watch = true
watch-additional-files = ["./src/**/*"]
features = ["ssr", "hydrate"]
