[package]
name = "sol-tools"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "sol-tools"
path = "src/main.rs"

[[bin]]
name = "create_spl"
path = "src/bin/create_spl.rs"

[dependencies]
actix-files = { version = "0.6", optional = true }
actix-web = { version = "4.0", optional = true }
console_error_panic_hook = "0.1"
http = { version = "1.0.0", optional = true }
leptos = { version = "0.6.5" }
leptos_meta = { version = "0.6.5" }
leptos_actix = { version = "0.6.5", optional = true }
leptos_router = { version = "0.6.5" }
wasm-bindgen = "0.2.93"
web-sys = { version = "0.3", features = ["Event", "SubmitEvent", "HtmlElement", "Window", "Document", "Storage", "Performance", "File", "FileList", "HtmlInputElement"] }
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
gloo-utils = "0.2"
serde_json = "1.0"
anyhow = "1.0"
serde-wasm-bindgen = "0.6"
borsh = "0.10.3"
borsh-derive = "0.10.3"
url = "2.5.0"
solana-program = { version = "1.17.12", optional = true }
solana-client = { version = "1.17.12", optional = true }
solana-sdk = { version = "1.17.12", optional = true }
spl-token = { version = "4.0", features = ["no-entrypoint"], optional = true }
spl-associated-token-account = { version = "2.3", features = ["no-entrypoint"], optional = true }
mpl-token-metadata = { version = "1.13", features = ["no-entrypoint"], optional = true }
tokio = { version = "1.35.1", features = ["full"], optional = true }
dotenv = "0.15.0"
reqwest = { version = "0.11", features = ["json", "rustls-tls"], default-features = false }
base58 = "0.1.0"
envy = "0.4"
mio = "0.8.11"
zstd-sys = { version = "2.0.9", features = ["pkg-config"], default-features = false }

[features]
default = ["ssr"]
csr = ["leptos/csr", "leptos_meta/csr", "leptos_router/csr"]
hydrate = ["leptos/hydrate", "leptos_meta/hydrate", "leptos_router/hydrate"]
ssr = [
    "dep:actix-files",
    "dep:actix-web",
    "dep:leptos_actix",
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr",
    "dep:http",
    "dep:tokio",
    "dep:solana-program",
    "dep:solana-client",
    "dep:solana-sdk",
    "dep:spl-token",
    "dep:spl-associated-token-account",
    "dep:mpl-token-metadata"
]
cli = [
    "dep:solana-program",
    "dep:solana-client",
    "dep:solana-sdk",
    "dep:spl-token",
    "dep:spl-associated-token-account",
    "dep:mpl-token-metadata",
    "dep:tokio"
]

[package.metadata.leptos]
output-name = "sol-tools"
site-root = "target/site"
site-pkg-dir = "pkg"
style-file = "style/main.scss"
assets-dir = "assets"
site-addr = "127.0.0.1:3000"
reload-port = 3001
end2end-cmd = "npx playwright test"
end2end-dir = "end2end"
browserquery = "defaults"
env = { "PINATA_API_KEY" = "", "PINATA_SECRET_API_KEY" = "", "SOLANA_SECRET_KEY" = "" }
bin-target = "sol-tools"
